### ISSUE TITLE
Problems with install and use

### ISSUE THREAD

**Issue by criphg** [RitataLU/MethylC-analyzer#2]
I tried to install your tool following in both options:
Using docker:

$docker pull peiyulin/methylc
Using default tag: latest
Error response from daemon: manifest for peiyulin/methylc:latest not found: manifest unknown: manifest unknown

Using command line (after installl dependencies and following the instructions):
$ python MethylC.py samples_list.txt TAR10_2_demo.gtf -a MT -b WT -d 4 -r 200 -q 2 -bs 200000 -pvalue 0.1
usage: MethylC.py [-h] [-a GROUP1] [-b GROUP2] [-d DEPTH] [-r REGION]
                  [-q QUALIFIED] [-context CONTEXT] [-hc HEATMAP_CUTOFF]
                  [-dmrc DMR_CUTOFF] [-test TESTMETHOD] [-pvalue PVALUE]
                  [-bs BIN_SIZE] [-p PROMOTER_SIZE]
                  command samples_list input_gtf_file path_to_files
MethylC.py: error: the following arguments are required: input_gtf_file, path_to_files

Could you help me?

**Comment by beritlin** [comment]
hello, 

for the docker version, please try `docker pull peiyulin/methylc:V1.0`.
